import type { Question } from './types'

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: 'seed-a-simbolismo-01',
    text: 'En el simbolismo masónico general, ¿qué representa principalmente la piedra bruta?',
    category: 'Simbolismo',
    difficulty: 'aprendiz',
    options: ['El trabajo personal aún por perfeccionar', 'La riqueza material', 'La antigüedad de una Logia', 'El rango administrativo'],
    correctAnswer: 0,
    directAnswer: 'El trabajo personal aún por perfeccionar',
    acceptedDirectAnswers: ['Trabajo personal', 'Perfeccionamiento personal', 'El individuo por perfeccionar'],
    explanation: 'La piedra bruta suele emplearse como símbolo del ser humano y del trabajo de perfeccionamiento sobre sí mismo.',
  },
  {
    id: 'seed-a-herramientas-01',
    text: '¿Qué idea simboliza comúnmente la escuadra?',
    category: 'Herramientas',
    difficulty: 'aprendiz',
    options: ['Rectitud en la conducta', 'Velocidad en el trabajo', 'Memoria histórica', 'Silencio absoluto'],
    correctAnswer: 0,
    directAnswer: 'Rectitud en la conducta',
    acceptedDirectAnswers: ['Rectitud', 'Conducta recta'],
  },
  {
    id: 'seed-a-filosofia-01',
    text: '¿Cuál de estas actitudes encaja mejor con la idea masónica de trabajar sobre uno mismo?',
    category: 'Filosofía',
    difficulty: 'aprendiz',
    options: ['Examinar y corregir los propios defectos', 'Competir por títulos', 'Evitar toda crítica', 'Memorizar sin comprender'],
    correctAnswer: 0,
    directAnswer: 'Examinar y corregir los propios defectos',
    acceptedDirectAnswers: ['Corregir los propios defectos', 'Mejoramiento personal', 'Autoconocimiento y mejora'],
  },
  {
    id: 'seed-a-historia-01',
    text: '¿De qué tradición toma la masonería especulativa buena parte de su lenguaje simbólico?',
    category: 'Historia',
    difficulty: 'aprendiz',
    options: ['De los antiguos oficios de constructores y canteros', 'De la navegación mercante', 'De la medicina medieval', 'De la caballería deportiva'],
    correctAnswer: 0,
    directAnswer: 'De los antiguos oficios de constructores y canteros',
    acceptedDirectAnswers: ['Constructores y canteros', 'Masones operativos', 'Cantería'],
  },
  {
    id: 'seed-a-artes-01',
    text: '¿Qué disciplina estudia las propiedades y relaciones de puntos, líneas, superficies y cuerpos?',
    category: 'Artes y Ciencias',
    difficulty: 'aprendiz',
    options: ['Geometría', 'Retórica', 'Música', 'Gramática'],
    correctAnswer: 0,
    directAnswer: 'Geometría',
  },
  {
    id: 'seed-a-ceremonial-01',
    text: '¿Por qué el orden y la secuencia tienen importancia en una ceremonia simbólica?',
    category: 'Ceremonial',
    difficulty: 'aprendiz',
    options: ['Porque ayudan a transmitir ideas mediante una experiencia estructurada', 'Porque sustituyen todo estudio personal', 'Porque eliminan la necesidad de símbolos', 'Porque todos los ritos son idénticos'],
    correctAnswer: 0,
    directAnswer: 'Porque ayudan a transmitir ideas mediante una experiencia estructurada',
    acceptedDirectAnswers: ['Transmitir ideas de forma estructurada', 'Dar estructura a la enseñanza simbólica'],
  },

  {
    id: 'seed-c-simbolismo-01',
    text: 'En el simbolismo masónico, ¿qué idea se asocia habitualmente con el nivel?',
    category: 'Simbolismo',
    difficulty: 'compañero',
    options: ['Igualdad esencial entre las personas', 'Superioridad intelectual', 'Aislamiento del mundo', 'Jerarquía económica'],
    correctAnswer: 0,
    directAnswer: 'Igualdad esencial entre las personas',
    acceptedDirectAnswers: ['Igualdad', 'Igualdad entre las personas'],
  },
  {
    id: 'seed-c-herramientas-01',
    text: '¿Qué enseñanza representa comúnmente la plomada?',
    category: 'Herramientas',
    difficulty: 'compañero',
    options: ['Verticalidad y conducta íntegra', 'Acumulación de conocimiento', 'Rapidez para decidir', 'Autoridad sobre los demás'],
    correctAnswer: 0,
    directAnswer: 'Verticalidad y conducta íntegra',
    acceptedDirectAnswers: ['Rectitud vertical', 'Conducta íntegra', 'Verticalidad'],
  },
  {
    id: 'seed-c-filosofia-01',
    text: '¿Qué diferencia describe mejor el paso de aprender datos a comprenderlos?',
    category: 'Filosofía',
    difficulty: 'compañero',
    options: ['Relacionar lo aprendido y encontrar su significado', 'Repetirlo más rápido', 'Evitar preguntas nuevas', 'Reducirlo a una sola frase'],
    correctAnswer: 0,
    directAnswer: 'Relacionar lo aprendido y encontrar su significado',
    acceptedDirectAnswers: ['Comprender su significado', 'Relacionar y comprender'],
  },
  {
    id: 'seed-c-historia-01',
    text: '¿Qué distingue, en términos generales, a la masonería especulativa de la masonería operativa?',
    category: 'Historia',
    difficulty: 'compañero',
    options: ['Usa el oficio de la construcción como lenguaje simbólico y moral', 'Construye únicamente edificios religiosos', 'Elimina las herramientas como símbolos', 'Se dedica profesionalmente a la cantería'],
    correctAnswer: 0,
    directAnswer: 'Usa el oficio de la construcción como lenguaje simbólico y moral',
    acceptedDirectAnswers: ['Usa la construcción de forma simbólica', 'Transforma el oficio en simbolismo moral'],
  },
  {
    id: 'seed-c-artes-01',
    text: '¿Cuál de las siguientes pertenece al conjunto tradicional de las siete artes liberales?',
    category: 'Artes y Ciencias',
    difficulty: 'compañero',
    options: ['Retórica', 'Arquitectura naval', 'Química orgánica', 'Economía'],
    correctAnswer: 0,
    directAnswer: 'Retórica',
  },
  {
    id: 'seed-c-ceremonial-01',
    text: 'En una enseñanza iniciática, ¿qué función cumple mejor un recorrido o viaje simbólico?',
    category: 'Ceremonial',
    difficulty: 'compañero',
    options: ['Representar un proceso progresivo de aprendizaje y transformación', 'Sustituir las obligaciones éticas', 'Determinar la antigüedad física del templo', 'Establecer una competencia entre participantes'],
    correctAnswer: 0,
    directAnswer: 'Representar un proceso progresivo de aprendizaje y transformación',
    acceptedDirectAnswers: ['Proceso de aprendizaje', 'Transformación progresiva', 'Progreso iniciático'],
  },

  {
    id: 'seed-m-simbolismo-01',
    text: '¿Qué tema filosófico adquiere especial relevancia en el simbolismo tradicional del tercer grado?',
    category: 'Simbolismo',
    difficulty: 'maestro',
    options: ['La mortalidad, el legado y la renovación', 'La riqueza personal', 'La competencia entre Logias', 'La administración financiera'],
    correctAnswer: 0,
    directAnswer: 'La mortalidad, el legado y la renovación',
    acceptedDirectAnswers: ['Mortalidad y renovación', 'Muerte, legado y renovación', 'La mortalidad'],
  },
  {
    id: 'seed-m-herramientas-01',
    text: 'Cuando una herramienta de construcción se interpreta simbólicamente, ¿qué lectura es más propia de la masonería especulativa?',
    category: 'Herramientas',
    difficulty: 'maestro',
    options: ['Convertir su función práctica en una enseñanza sobre la conducta', 'Usarla únicamente como decoración', 'Eliminar su significado operativo', 'Asignarle un valor económico fijo'],
    correctAnswer: 0,
    directAnswer: 'Convertir su función práctica en una enseñanza sobre la conducta',
    acceptedDirectAnswers: ['Transformar su función en enseñanza moral', 'Usarla como enseñanza de conducta'],
  },
  {
    id: 'seed-m-filosofia-01',
    text: '¿Qué actitud expresa mejor la idea de maestría entendida como perfeccionamiento continuo?',
    category: 'Filosofía',
    difficulty: 'maestro',
    options: ['Aplicar, revisar y perfeccionar de manera constante lo aprendido', 'Considerar terminado todo aprendizaje', 'Depender sólo de la memoria', 'Evitar enseñar a otros'],
    correctAnswer: 0,
    directAnswer: 'Aplicar, revisar y perfeccionar de manera constante lo aprendido',
    acceptedDirectAnswers: ['Perfeccionar continuamente lo aprendido', 'Aplicar y perfeccionar'],
  },
  {
    id: 'seed-m-historia-01',
    text: '¿Por qué es importante distinguir entre hechos históricos documentados y tradiciones simbólicas al estudiar masonería?',
    category: 'Historia',
    difficulty: 'maestro',
    options: ['Porque cumplen funciones distintas y no deben confundirse como el mismo tipo de evidencia', 'Porque la tradición siempre invalida los documentos', 'Porque los símbolos carecen de valor', 'Porque toda narración simbólica es necesariamente un hecho histórico'],
    correctAnswer: 0,
    directAnswer: 'Porque cumplen funciones distintas y no deben confundirse como el mismo tipo de evidencia',
    acceptedDirectAnswers: ['Porque historia y tradición simbólica son evidencias distintas', 'Distinguir evidencia histórica de simbolismo'],
  },
  {
    id: 'seed-m-artes-01',
    text: '¿Qué relación simbólica puede establecerse entre geometría y construcción moral?',
    category: 'Artes y Ciencias',
    difficulty: 'maestro',
    options: ['La medida y la proporción pueden representar orden, equilibrio y disciplina', 'La geometría reemplaza toda ética', 'Las figuras determinan el rango de una persona', 'La proporción sólo tiene valor ornamental'],
    correctAnswer: 0,
    directAnswer: 'La medida y la proporción pueden representar orden, equilibrio y disciplina',
    acceptedDirectAnswers: ['Orden equilibrio y disciplina', 'Medida y proporción como orden moral'],
  },
  {
    id: 'seed-m-ceremonial-01',
    text: '¿Cuál es la mejor manera de estudiar una ceremonia de un rito específico sin confundirla con otras jurisdicciones?',
    category: 'Ceremonial',
    difficulty: 'maestro',
    options: ['Usar la liturgia y las fuentes autorizadas de ese rito y jurisdicción', 'Suponer que todas las Logias trabajan exactamente igual', 'Tomar cualquier video como fuente definitiva', 'Ignorar las diferencias rituales'],
    correctAnswer: 0,
    directAnswer: 'Usar la liturgia y las fuentes autorizadas de ese rito y jurisdicción',
    acceptedDirectAnswers: ['Consultar la liturgia autorizada', 'Usar fuentes del rito y jurisdicción'],
  },
]
