import type { Question } from './types'

const rows: Array<[string, string, string, string[], number]> = [
  ['hist-01', 'Historia', '¿En qué año inició la Independencia de México?', ['1810', '1821', '1910', '1812'], 0],
  ['hist-02', 'Historia', '¿Qué civilización construyó Machu Picchu?', ['Maya', 'Inca', 'Azteca', 'Olmeca'], 1],
  ['hist-03', 'Historia', '¿Qué acontecimiento comenzó en 1910 en México?', ['La Independencia', 'La Revolución Mexicana', 'La Reforma', 'La Guerra de los Pasteles'], 1],
  ['geo-01', 'Geografía', '¿Cuál es el océano más grande del planeta?', ['Atlántico', 'Índico', 'Pacífico', 'Ártico'], 2],
  ['geo-02', 'Geografía', '¿Cuál es la capital de Canadá?', ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], 2],
  ['geo-03', 'Geografía', '¿En qué continente se encuentra Egipto?', ['Asia únicamente', 'África', 'Europa', 'Oceanía'], 1],
  ['ciencia-01', 'Ciencia', '¿Cuál es el planeta más cercano al Sol?', ['Venus', 'Mercurio', 'Marte', 'Tierra'], 1],
  ['ciencia-02', 'Ciencia', '¿Qué gas utiliza principalmente el cuerpo humano para la respiración celular?', ['Nitrógeno', 'Oxígeno', 'Helio', 'Neón'], 1],
  ['ciencia-03', 'Ciencia', '¿Cuál es la fórmula química del agua?', ['CO2', 'O2', 'H2O', 'NaCl'], 2],
  ['cultura-01', 'Cultura', '¿Quién escribió Don Quijote de la Mancha?', ['Miguel de Cervantes', 'Gabriel García Márquez', 'Pablo Neruda', 'Octavio Paz'], 0],
  ['cultura-02', 'Cultura', '¿Cuál es el idioma con más hablantes nativos en el mundo?', ['Inglés', 'Español', 'Mandarín', 'Francés'], 2],
  ['cultura-03', 'Cultura', '¿Qué celebración mexicana se conmemora tradicionalmente el 1 y 2 de noviembre?', ['Día de Muertos', 'Grito de Independencia', 'Día de la Bandera', 'Revolución Mexicana'], 0],
  ['mate-01', 'Matemáticas', '¿Cuánto es 12 × 8?', ['86', '96', '108', '88'], 1],
  ['mate-02', 'Matemáticas', '¿Cuál es el resultado de 144 ÷ 12?', ['10', '11', '12', '14'], 2],
  ['mate-03', 'Matemáticas', 'Un triángulo tiene ángulos de 50° y 60°. ¿Cuánto mide el tercero?', ['60°', '70°', '80°', '90°'], 1],
  ['lengua-01', 'Lengua', '¿Cuál es un sinónimo de “rápido”?', ['Lento', 'Veloz', 'Pesado', 'Lejano'], 1],
  ['lengua-02', 'Lengua', '¿Cuál de estas palabras es un verbo?', ['Mesa', 'Azul', 'Correr', 'Grande'], 2],
  ['lengua-03', 'Lengua', '¿Qué signo se usa para abrir una pregunta en español?', ['!', '¿', ';', ':'], 1],
  ['tec-01', 'Tecnología', '¿Qué significa normalmente CPU en informática?', ['Unidad Central de Procesamiento', 'Control Público Universal', 'Código Personal de Usuario', 'Unidad de Potencia Continua'], 0],
  ['tec-02', 'Tecnología', '¿Cuál de estos es un sistema operativo?', ['Linux', 'HTML', 'USB', 'JPEG'], 0],
  ['tec-03', 'Tecnología', '¿Qué protocolo se usa habitualmente para páginas web seguras?', ['FTP', 'HTTPS', 'SMTP', 'Bluetooth'], 1],
  ['arte-01', 'Arte', '¿Quién pintó La noche estrellada?', ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Diego Rivera'], 1],
  ['arte-02', 'Arte', '¿Quién pintó la Mona Lisa?', ['Leonardo da Vinci', 'Miguel Ángel', 'Rembrandt', 'Dalí'], 0],
  ['arte-03', 'Arte', '¿Cuál de estos instrumentos tiene teclas y cuerdas en su interior?', ['Piano', 'Flauta', 'Trompeta', 'Clarinete'], 0],
  ['dep-01', 'Deportes', '¿Cuántos jugadores de un equipo de fútbol están normalmente en cancha al iniciar un partido?', ['9', '10', '11', '12'], 2],
  ['dep-02', 'Deportes', '¿En qué deporte se utiliza una canasta y un balón que se bota con la mano?', ['Tenis', 'Baloncesto', 'Béisbol', 'Golf'], 1],
  ['dep-03', 'Deportes', '¿Cuántos puntos vale un tiro libre convertido en baloncesto?', ['1', '2', '3', '4'], 0],
  ['mix-01', 'Ciencia', '¿Qué órgano bombea la sangre por el cuerpo?', ['Pulmón', 'Corazón', 'Hígado', 'Riñón'], 1],
  ['mix-02', 'Geografía', '¿Cuál es el país más grande del mundo por superficie?', ['Canadá', 'China', 'Rusia', 'Estados Unidos'], 2],
  ['mix-03', 'Historia', '¿Quién fue el primer ser humano en pisar la Luna?', ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], 1],
]

export const FREE_GENERAL_QUESTIONS: Question[] = rows.map(([id, category, text, options, correctAnswer]) => ({
  id: `libre-${id}`,
  rite: 'libre',
  difficulty: 'general',
  category,
  text,
  options,
  correctAnswer,
  directAnswer: options[correctAnswer],
  source: 'Banco de cultura general incluido en el juego. Este contenido no es masónico.',
  basePoints: 10,
}))
