import type { Question } from './types'

const APPRENTICE_SOURCE = 'Liturgia Única del Grado de Aprendiz atribuida a la Gran Logia de Libres y Aceptados Masones de Nuevo León (copia pública indexada).'
const COMPANION_SOURCE = 'Instrucción pública de Segundo Grado del REAA y material de estudio de Compañero; adaptar a la liturgia vigente de la jurisdicción.'
const MASTER_SOURCE = 'Liturgia Única del Grado de Maestro Masón atribuida a la Gran Logia de Libres y Aceptados Masones de Nuevo León y rituales públicos REAA (copias públicas indexadas).'

const base = (item: Omit<Question, 'rite'>): Question => ({ ...item, rite: 'reaa' })

export const REAA_NUEVO_LEON_QUESTIONS: Question[] = [
  // APRENDIZ — segundo bloque, orientado a la liturgia pública de Nuevo León
  base({ id:'reaa-nl-a-historia-02', difficulty:'aprendiz', category:'Historia', source:APPRENTICE_SOURCE,
    text:'Según la introducción tradicional de la liturgia, ¿qué medios utiliza la Masonería para procurar el perfeccionamiento del hombre?',
    options:['El estudio de ciencias, artes y moral, junto con la práctica de virtudes y fraternidad','La acumulación de grados por antigüedad','El aislamiento de la sociedad','La obediencia política a una sola doctrina'], correctAnswer:0,
    directAnswer:'El estudio de ciencias, artes y moral, y la práctica de virtudes y fraternidad', acceptedDirectAnswers:['Ciencias artes moral virtudes fraternidad','Estudio y práctica de virtudes'],
    explanation:'La formación masónica se presenta como intelectual, moral y fraternal, no como simple acumulación de grados.' }),
  base({ id:'reaa-nl-a-filosofia-02', difficulty:'aprendiz', category:'Filosofía', source:APPRENTICE_SOURCE,
    text:'En una instrucción de Aprendiz, ¿qué se entiende principalmente por Masonería?',
    options:['El estudio de la Filosofía y particularmente de la Moral para conocer y practicar las virtudes','Una escuela de arquitectura profesional','Una asociación dedicada a obtener privilegios','Una religión que sustituye las creencias personales'], correctAnswer:0,
    directAnswer:'El estudio de la Filosofía y de la Moral para practicar las virtudes', acceptedDirectAnswers:['Filosofía y moral','Estudio de la filosofía para practicar virtudes'] }),
  base({ id:'reaa-nl-a-geometria-02', difficulty:'aprendiz', category:'Geometría', source:APPRENTICE_SOURCE,
    text:'En la idea tradicional de una Logia Simple, Justa y Perfecta, ¿qué progresión numérica aparece?',
    options:['3, 5 y 7','2, 4 y 6','4, 8 y 12','1, 3 y 9'], correctAnswer:0,
    directAnswer:'3, 5 y 7', acceptedDirectAnswers:['Tres cinco siete','3 5 7'],
    explanation:'La instrucción describe tres masones para una Logia Simple, cinco para una Justa y siete para una Perfecta.' }),
  base({ id:'reaa-nl-a-etica-02', difficulty:'aprendiz', category:'Ética', source:APPRENTICE_SOURCE,
    text:'¿Cuál de estas descripciones se aproxima mejor al ideal de un masón presentado al Aprendiz?',
    options:['Hombre libre, honrado, virtuoso, amante de su patria y fiel a sus leyes','Hombre que busca privilegios sobre los demás','Persona que renuncia a toda opinión propia','Miembro que sólo debe memorizar ceremonias'], correctAnswer:0,
    directAnswer:'Hombre libre, honrado y virtuoso, amante de su patria y fiel a sus leyes', acceptedDirectAnswers:['Libre honrado virtuoso','Hombre libre y virtuoso'] }),
  base({ id:'reaa-nl-a-tradicion-02', difficulty:'aprendiz', category:'Tradición', source:APPRENTICE_SOURCE,
    text:'¿Qué tres dignidades son presentadas como las “tres luces” de la Logia en la instrucción de Aprendiz?',
    options:['Venerable Maestro, Primer Vigilante y Segundo Vigilante','Secretario, Tesorero y Hospitalario','Orador, Experto y Diácono','Portabandera, Ecónomo y Guarda Templo'], correctAnswer:0,
    directAnswer:'Venerable Maestro, Primer Vigilante y Segundo Vigilante', acceptedDirectAnswers:['Venerable y dos vigilantes','VM primer vigilante segundo vigilante'] }),
  base({ id:'reaa-nl-a-simbolismo-02', difficulty:'aprendiz', category:'Simbolismo', source:APPRENTICE_SOURCE,
    text:'Si la piedra bruta representa el estado de imperfección, ¿qué dos causas menciona expresamente la enseñanza tradicional?',
    options:['Los vicios y la ignorancia','La pobreza y la juventud','El silencio y la prudencia','La ciencia y la curiosidad'], correctAnswer:0,
    directAnswer:'Los vicios y la ignorancia', acceptedDirectAnswers:['Vicios e ignorancia','Vicio e ignorancia'] }),
  base({ id:'reaa-nl-a-herramientas-02', difficulty:'aprendiz', category:'Herramientas', source:APPRENTICE_SOURCE,
    text:'Relaciona correctamente las joyas de las tres principales dignidades: Venerable Maestro, Primer Vigilante y Segundo Vigilante.',
    options:['Escuadra, Nivel y Plomada','Compás, Cincel y Palanca','Regla, Mazo y Libro','Plomada, Espada y Llave'], correctAnswer:0,
    directAnswer:'Escuadra, Nivel y Plomada', acceptedDirectAnswers:['Escuadra nivel plomada'] }),
  base({ id:'reaa-nl-a-artes-02', difficulty:'aprendiz', category:'Artes y Ciencias', source:APPRENTICE_SOURCE,
    text:'¿Qué combinación refleja mejor la formación que se propone desde el grado de Aprendiz?',
    options:['Ciencias, artes, filosofía y moral','Sólo memorización ritual','Únicamente geometría práctica','Solamente historia antigua'], correctAnswer:0,
    directAnswer:'Ciencias, artes, filosofía y moral', acceptedDirectAnswers:['Ciencias artes filosofía moral'] }),
  base({ id:'reaa-nl-a-ceremonial-02', difficulty:'aprendiz', category:'Ceremonial', source:APPRENTICE_SOURCE,
    text:'¿Qué simboliza el mandil que recibe el Aprendiz en la explicación tradicional?',
    options:['El trabajo','La riqueza','El rango político','La antigüedad'], correctAnswer:0,
    directAnswer:'El trabajo', acceptedDirectAnswers:['Trabajo'],
    explanation:'La liturgia lo presenta como distintivo del masón y símbolo del trabajo, asociado al saber y la virtud.' }),

  // COMPAÑERO — segundo bloque, preguntas de instrucción pública de segundo grado
  base({ id:'reaa-nl-c-historia-02', difficulty:'compañero', category:'Historia', source:COMPANION_SOURCE,
    text:'El paso al segundo grado se denomina tradicionalmente ¿de qué manera?',
    options:['Aumento de Salario','Exaltación al Oriente','Instalación Capitular','Consagración de Maestro'], correctAnswer:0,
    directAnswer:'Aumento de Salario', acceptedDirectAnswers:['Aumento de salario'] }),
  base({ id:'reaa-nl-c-filosofia-02', difficulty:'compañero', category:'Filosofía', source:COMPANION_SOURCE,
    text:'En el simbolismo del Compañero, “pasar de la perpendicular al nivel” expresa mejor ¿qué cambio?',
    options:['Ampliar el trabajo individual hacia una comprensión de igualdad y relación con los demás','Abandonar toda disciplina','Cambiar de profesión','Sustituir la moral por la fuerza'], correctAnswer:0,
    directAnswer:'Ampliar el trabajo hacia la igualdad y la relación con los demás', acceptedDirectAnswers:['De la perpendicular al nivel','Igualdad y relación con los demás'] }),
  base({ id:'reaa-nl-c-geometria-02', difficulty:'compañero', category:'Geometría', source:COMPANION_SOURCE,
    text:'¿Qué significado se atribuye de manera destacada a la letra G en muchas instrucciones del Compañero?',
    options:['Geometría','Gobierno','Guerra','Genealogía'], correctAnswer:0,
    directAnswer:'Geometría', acceptedDirectAnswers:['Geometria'] }),
  base({ id:'reaa-nl-c-etica-02', difficulty:'compañero', category:'Ética', source:COMPANION_SOURCE,
    text:'Si una decisión exige actuar correctamente pero también medir sus consecuencias, ¿qué virtud del Compañero resulta especialmente pertinente?',
    options:['Prudencia','Vanidad','Ambición','Imposición'], correctAnswer:0,
    directAnswer:'Prudencia', acceptedDirectAnswers:['La prudencia'] }),
  base({ id:'reaa-nl-c-tradicion-02', difficulty:'compañero', category:'Tradición', source:COMPANION_SOURCE,
    text:'¿Qué número se repite como clave simbólica del segundo grado en la edad y en diversos elementos de su instrucción?',
    options:['Cinco','Tres','Siete','Nueve'], correctAnswer:0,
    directAnswer:'Cinco', acceptedDirectAnswers:['5'] }),
  base({ id:'reaa-nl-c-simbolismo-02', difficulty:'compañero', category:'Simbolismo', source:COMPANION_SOURCE,
    text:'La Estrella Flamígera del segundo grado se relaciona mejor con ¿qué idea?',
    options:['La expansión de la luz, el conocimiento y la evolución del iniciado','La riqueza material','La jerarquía administrativa','El descanso después del trabajo'], correctAnswer:0,
    directAnswer:'La luz, el conocimiento y la evolución del iniciado', acceptedDirectAnswers:['Conocimiento y evolución','La luz y el conocimiento'] }),
  base({ id:'reaa-nl-c-herramientas-02', difficulty:'compañero', category:'Herramientas', source:COMPANION_SOURCE,
    text:'¿Qué enseñanza se atribuye tradicionalmente a la palanca durante los viajes del Compañero?',
    options:['El poder de la razón y la inteligencia aplicadas','La obediencia sin reflexión','La memoria de los hechos','El aislamiento personal'], correctAnswer:0,
    directAnswer:'El poder de la razón y la inteligencia', acceptedDirectAnswers:['Razón e inteligencia','Poder de la razón'] }),
  base({ id:'reaa-nl-c-artes-02', difficulty:'compañero', category:'Artes y Ciencias', source:COMPANION_SOURCE,
    text:'¿Cuáles pertenecen al Trivium dentro de las siete artes liberales?',
    options:['Gramática, Retórica y Lógica','Aritmética, Geometría y Música','Geometría, Música y Astronomía','Historia, Ética y Filosofía'], correctAnswer:0,
    directAnswer:'Gramática, Retórica y Lógica', acceptedDirectAnswers:['Gramática retórica lógica'] }),
  base({ id:'reaa-nl-c-ceremonial-02', difficulty:'compañero', category:'Ceremonial', source:COMPANION_SOURCE,
    text:'¿Cómo termina simbólicamente el quinto viaje del Compañero en varias versiones del REAA?',
    options:['Con las manos libres para observar y comprender','Cargando el mazo y el cincel','Con una espada y un libro','Con una plomada en cada mano'], correctAnswer:0,
    directAnswer:'Con las manos libres', acceptedDirectAnswers:['Manos libres','Sin herramientas'],
    explanation:'El último viaje suele representarse sin herramientas, enfatizando observación, reflexión y asimilación de lo aprendido.' }),

  // MAESTRO — segundo bloque, orientado a la liturgia pública de Nuevo León y REAA
  base({ id:'reaa-nl-m-historia-02', difficulty:'maestro', category:'Historia', source:MASTER_SOURCE,
    text:'¿Cuántos grados comprende la estructura completa del REAA en su formulación moderna?',
    options:['33','25','12','7'], correctAnswer:0, directAnswer:'33', acceptedDirectAnswers:['Treinta y tres','33 grados'] }),
  base({ id:'reaa-nl-m-filosofia-02', difficulty:'maestro', category:'Filosofía', source:MASTER_SOURCE,
    text:'En la liturgia de Maestro atribuida a Nuevo León, ¿qué facultad se destaca como aquello que distingue al hombre y debe conservarse íntegramente?',
    options:['La inteligencia','La fuerza física','La riqueza','La autoridad'], correctAnswer:0,
    directAnswer:'La inteligencia', acceptedDirectAnswers:['Inteligencia'] }),
  base({ id:'reaa-nl-m-geometria-02', difficulty:'maestro', category:'Geometría', source:MASTER_SOURCE,
    text:'La escalera simbólica asociada a la Cámara del Medio se organiza tradicionalmente con ¿qué números?',
    options:['3, 5 y 7','1, 2 y 4','4, 6 y 8','5, 10 y 15'], correctAnswer:0,
    directAnswer:'3, 5 y 7', acceptedDirectAnswers:['Tres cinco siete','3 5 7'] }),
  base({ id:'reaa-nl-m-etica-02', difficulty:'maestro', category:'Ética', source:MASTER_SOURCE,
    text:'¿Cuál de estas ternas contiene enemigos del progreso que el Maestro debe combatir según una formulación de la liturgia de Nuevo León?',
    options:['Ignorancia, hipocresía y ambición','Ciencia, tolerancia y fraternidad','Prudencia, estudio y valor','Justicia, verdad y filantropía'], correctAnswer:0,
    directAnswer:'Ignorancia, hipocresía y ambición', acceptedDirectAnswers:['Ignorancia hipocresía ambición'] }),
  base({ id:'reaa-nl-m-tradicion-02', difficulty:'maestro', category:'Tradición', source:MASTER_SOURCE,
    text:'¿Qué temas humanos fundamentales articula la dramatización central del tercer grado?',
    options:['Fidelidad, pérdida, búsqueda y renovación','Riqueza, comercio y poder','Competencia, triunfo y fama','Obediencia política y conquista'], correctAnswer:0,
    directAnswer:'Fidelidad, pérdida, búsqueda y renovación', acceptedDirectAnswers:['Pérdida búsqueda renovación','Fidelidad y renovación'] }),
  base({ id:'reaa-nl-m-simbolismo-02', difficulty:'maestro', category:'Simbolismo', source:MASTER_SOURCE,
    text:'Cuando la acacia aparece en la instrucción del Maestro, ¿qué lectura encaja mejor con su simbolismo?',
    options:['Persistencia de la vida, memoria y búsqueda de la luz y la verdad','Riqueza y poder temporal','Silencio administrativo','Superioridad de un rango'], correctAnswer:0,
    directAnswer:'Persistencia de la vida, memoria y búsqueda de la luz y la verdad', acceptedDirectAnswers:['Vida memoria luz verdad','Continuidad y renovación'] }),
  base({ id:'reaa-nl-m-herramientas-02', difficulty:'maestro', category:'Herramientas', source:MASTER_SOURCE,
    text:'Si la escuadra recuerda la rectitud, ¿qué función simbólica complementaria aporta el compás al Maestro?',
    options:['Medir, delimitar y gobernar sus propias acciones','Aumentar la fuerza física','Representar la antigüedad','Sustituir el juicio moral'], correctAnswer:0,
    directAnswer:'Medir y delimitar sus propias acciones', acceptedDirectAnswers:['Medida y límite','Gobernar sus acciones'] }),
  base({ id:'reaa-nl-m-artes-02', difficulty:'maestro', category:'Artes y Ciencias', source:MASTER_SOURCE,
    text:'¿Qué capacidad debe desarrollar el Maestro al integrar las enseñanzas previas de símbolos, artes y ciencias?',
    options:['Trazar criterios y orientar el trabajo con juicio propio','Dejar de estudiar','Repetir fórmulas sin interpretarlas','Evitar enseñar a otros'], correctAnswer:0,
    directAnswer:'Orientar el trabajo con juicio propio', acceptedDirectAnswers:['Trazar criterios','Guiar con juicio propio','Orientar el trabajo'] }),
  base({ id:'reaa-nl-m-ceremonial-02', difficulty:'maestro', category:'Ceremonial', source:MASTER_SOURCE,
    text:'¿Qué función pedagógica tiene la dramatización del tercer grado dentro del juego iniciático?',
    options:['Hacer vivir simbólicamente una reflexión sobre vida, muerte, fidelidad y renovación','Probar conocimientos de arquitectura profesional','Determinar el rango económico','Reemplazar la enseñanza moral por espectáculo'], correctAnswer:0,
    directAnswer:'Reflexionar sobre vida, muerte, fidelidad y renovación', acceptedDirectAnswers:['Vida muerte fidelidad renovación','Reflexión sobre vida y muerte'] }),
]
